version: '2'
services:
  server:
    container_name: UpcomingMoviesServer
    build: .
    command: npm run dev
    volumes:
      - .:/usr/app/
      - /usr/src/app/node_modules
    ports:
      - "80:80"
    environment:
      NODE_ENV: development
      SERVER_PORT: 80